version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - 'python3'
      - 'manage.py'
      - 'runserver'
      - '0.0.0.0:9080'
    ports:
      - '9000:9080'
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
